# Generated by Django 4.2.19 on 2025-02-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultytranscript',
            unique_together={('transcript_number',)},
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('myedu_spec_id', models.PositiveIntegerField(unique=True, verbose_name='MyEDU Специальность ID')),
                ('short_name', models.CharField(max_length=150, verbose_name='Короткое название')),
                ('visit', models.BooleanField(default=True, verbose_name='Показывать')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bsadmin.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
