# Generated by Django 4.2.19 on 2025-02-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0003_speciality_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtranscript',
            name='faculty_history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='История факультета'),
        ),
        migrations.AddField(
            model_name='registrationtranscript',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bsadmin.speciality', verbose_name='Специальность студента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationtranscript',
            name='speciality_history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='История специальности'),
        ),
    ]
