# Generated by Django 4.2.19 on 2025-03-04 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0004_registrationtranscript_faculty_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='category',
            field=models.CharField(blank=True, choices=[('CLE', 'Колледж'), ('FACT', 'Факультет'), ('SCH', 'Школа')], default='FACT', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registrationtranscript',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultytranscript',
            name='transcript_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Введите № академической справки'),
        ),
    ]
