# Generated by Django 4.2.19 on 2025-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0005_faculty_category_registrationtranscript_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranscript',
            name='category',
            field=models.CharField(blank=True, choices=[('CLE', 'Колледж'), ('FACT', 'Факультет'), ('SCH', 'Школа')], default='FACT', max_length=15, null=True),
        ),
    ]
