# Generated by Django 4.2.19 on 2025-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0006_categorytranscript_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_myedu',
            field=models.BooleanField(default=True, verbose_name='Факультет MyEDU ?'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='myedu_faculty_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MyEDU Факультет ID'),
        ),
    ]
