# Generated by Django 4.2.19 on 2025-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0007_faculty_is_myedu_alter_faculty_myedu_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHistoryTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_number', models.CharField(max_length=255, verbose_name='Номер транскрипта')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('student_uuid', models.CharField(max_length=100, verbose_name='Уникальный номер студента')),
                ('student_fio', models.CharField(max_length=150, verbose_name='ФИО студента')),
                ('faculty', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО студента')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='История специальности')),
            ],
            options={
                'verbose_name': 'История регистрации студента',
                'verbose_name_plural': 'Истории регистрации студентов',
            },
        ),
    ]
