# Generated by Django 4.2.19 on 2025-12-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0008_reghistorytranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='reghistorytranscript',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
