# Generated by Django 4.2.19 on 2026-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0009_reghistorytranscript_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='myedu_spec_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MyEDU Специальность ID'),
        ),
    ]
