# Generated by Django 4.2.19 on 2025-10-23 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stepper', '0006_issuance_passport_archive'),
        ('bsadmin', '0007_faculty_is_myedu_alter_faculty_myedu_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('confirm_date', models.DateField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('bundle_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер связки')),
                ('rack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стеллаж')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
            },
        ),
        migrations.CreateModel(
            name='CategoryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=50, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Форма категория',
                'verbose_name_plural': 'Форма категории',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документа',
            },
        ),
        migrations.CreateModel(
            name='EduForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('template_text', models.TextField(blank=True, null=True, verbose_name='Шаблон текста')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Форма обучения',
            },
        ),
        migrations.CreateModel(
            name='StudentsAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myedu_id', models.CharField(blank=True, help_text='Студент, которому принадлежит обходной лист.', max_length=255, null=True, verbose_name='Студент номер из MyEDU')),
                ('order_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата приказа')),
                ('order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приказ')),
                ('order_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус')),
                ('student_fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('status', models.BooleanField(default=False, verbose_name='Статус возвращения')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возвращения')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('doc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.acts', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Акт студентов',
                'verbose_name_plural': 'Акты студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус возвращения')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возвращения')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('doc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('doc_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.documentcategory', verbose_name='Категория документа')),
                ('student_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.studentsact', verbose_name='Акт студента')),
            ],
            options={
                'verbose_name': 'Документ студента',
                'verbose_name_plural': 'Документы студента',
            },
        ),
        migrations.CreateModel(
            name='StudentDocFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='transcripts/fails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.validator.validate_file_size], verbose_name='Документ')),
                ('student_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.studentdocuments', verbose_name='Документ студента')),
            ],
            options={
                'verbose_name': 'Загружаемый документ',
                'verbose_name_plural': 'Загруженные документы',
            },
        ),
        migrations.AddField(
            model_name='acts',
            name='category_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.categoryform', verbose_name='Форма категории'),
        ),
        migrations.AddField(
            model_name='acts',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_user', to=settings.AUTH_USER_MODEL, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='acts',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ok_user', to=settings.AUTH_USER_MODEL, verbose_name='Отдел кадров'),
        ),
        migrations.AddField(
            model_name='acts',
            name='edu_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.eduform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='acts',
            name='edu_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stepper.eduyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='acts',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bsadmin.faculty', verbose_name='Факультет'),
        ),
    ]
