STSURVE = "stsurve"

SURVEY_COMPLETIONS_PAGE_SIZE = 100

SURVEY_QUESTION_TEXT_MIN = 3
SURVEY_QUESTION_TEXT_MAX = 2000
SURVEY_OPTION_TEXT_MIN = 1
SURVEY_OPTION_TEXT_MAX = 500
SURVEY_OPTIONS_MIN = 2
SURVEY_OPTIONS_MAX = 20
SURVEY_CUSTOM_TEXT_MIN = 1
SURVEY_CUSTOM_TEXT_MAX = 2000
