# Generated by Django 4.2.19 on 2025-04-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0006_categorytranscript_category'),
        ('stepper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные года',
            },
        ),
        migrations.AlterField(
            model_name='clearancesheet',
            name='myedu_id',
            field=models.CharField(help_text='Студент, которому принадлежит обходной лист.', max_length=255, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='student',
            field=models.CharField(help_text='Студент, которому принадлежит обходной лист.', max_length=255, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='issuancehistory',
            name='student',
            field=models.CharField(help_text='Студент, которому принадлежит обходной лист.', max_length=255, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(help_text='Студент, которому принадлежит диплом.', max_length=255, verbose_name='Студент')),
                ('doc_number', models.CharField(max_length=255, verbose_name='Дипломный номер')),
                ('reg_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный номер')),
                ('gak_date', models.DateField(blank=True, null=True, verbose_name='Дата ГАК')),
                ('date_issue', models.DateField(blank=True, help_text='Дата выдачи обходного листа', null=True, verbose_name='Дата выдачи')),
                ('sync', models.BooleanField(default=False, verbose_name='Синхронизировался')),
                ('edu_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stepper.eduyear', verbose_name='Учебный год')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bsadmin.faculty', verbose_name='Факультет студента')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bsadmin.speciality', verbose_name='Специальность студента')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
            },
        ),
    ]
