# Generated by Django 4.2.19 on 2025-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0002_eduyear_alter_clearancesheet_myedu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancesheet',
            name='last_active',
            field=models.BooleanField(default=True, verbose_name='Последний активный обходной'),
        ),
    ]
