# Generated by Django 4.2.19 on 2025-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0003_clearancesheet_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='document/profile/'),
        ),
    ]
