# Generated by Django 4.2.19 on 2025-08-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0004_issuance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancesheet',
            name='edu_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stepper.eduyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='eduyear',
            name='commission_active',
            field=models.BooleanField(default=False),
        ),
    ]
