# Generated by Django 4.2.19 on 2025-08-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0005_clearancesheet_edu_year_eduyear_commission_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='passport_archive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт (архив)'),
        ),
    ]
