# Generated by Django 4.2.19 on 2026-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0007_useractionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Номер справки')),
                ('student_id', models.CharField(max_length=50, verbose_name='ID Студента')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('birth_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='Информация о рождении')),
                ('faculty_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Факультет')),
                ('specialty_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность и уровень')),
                ('study_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения')),
                ('payment_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма оплаты')),
                ('study_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок освоения программы')),
                ('current_course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текущий курс')),
                ('order_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация о приказе')),
                ('fall_semester', models.CharField(blank=True, max_length=255, null=True, verbose_name='Осенний семестр')),
                ('spring_semester', models.CharField(blank=True, max_length=255, null=True, verbose_name='Весенний семестр')),
                ('vacation_period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Каникулярный период')),
                ('lang', models.CharField(default='ru', max_length=10, verbose_name='Язык справки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Каникулярная справка',
                'verbose_name_plural': 'Каникулярные справки',
            },
        ),
    ]
