# Generated by Django 4.2.19 on 2026-03-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepper', '0008_vacationcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationcertificate',
            name='edu_year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уччебный год'),
        ),
    ]
