# Generated by Django 4.2.19 on 2026-06-30 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stepper', '0010_vacationcertificate_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('student_fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('student_login', models.CharField(max_length=150, verbose_name='Логин')),
                ('student_group', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('edu_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_submissions', to='stepper.eduyear', verbose_name='Учебный год')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='student.survey', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прохождение анкеты',
                'verbose_name_plural': 'Прохождения анкет',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('radio', 'Один вариант ответа'), ('checkbox', 'Несколько вариантов ответа')], max_length=20, verbose_name='Тип вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.survey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Вопрос анкеты',
                'verbose_name_plural': 'Вопросы анкеты',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='student.surveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_items', to='student.surveyoption', verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_items', to='student.surveyquestion', verbose_name='Вопрос')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student.surveysubmission', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_phone', models.CharField(max_length=20, validators=[student.models.validate_work_phone], verbose_name='Рабочий телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
        migrations.AddConstraint(
            model_name='surveysubmission',
            constraint=models.UniqueConstraint(fields=('user', 'survey', 'edu_year'), name='unique_survey_submission_per_year'),
        ),
        migrations.AddConstraint(
            model_name='surveyansweritem',
            constraint=models.UniqueConstraint(fields=('submission', 'question', 'option'), name='unique_survey_answer_option'),
        ),
    ]
